apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-proxy-env
  namespace: cjoc1
data:
  HTTP_PROXY: "http://squid-dev-proxy.squid.svc.cluster.local:3128"
  HTTPS_PROXY: "http://squid-dev-proxy.squid.svc.cluster.local:3128"
  NO_PROXY: "localhost,127.0.0.1,.svc.cluster.local,.cluster.local,.beescloud.com"
